### ISSUE TITLE
Would like an option for the opposite

### ISSUE THREAD

**Issue by Gitoffthelawn** [jaens/no-pdf-download#1]
Thank you for the nice extension.

I would love to see an option for it where the user can quickly (perhaps via a toolbar icon and/or a keyboard shortcut) toggle to the exact opposite behaviour: *always* downloading PDF files instead of opening them in Firefox.

Thanks!

**Comment by jaens** [comment]
That's an interesting idea, I'm not sure what Firefox will do if you try to "open" an attachment (ie. download) in an embedded `<iframe>` (as some sites do), might check it out when I get some time though!

**Comment by Gitoffthelawn** [comment]
Thanks!  Look forward to it whenever you have the time.

**Comment by jaens** [comment]
Beta of this is live on AMO now with version 2.1.0, feel free to leave extra feedback here.
The feature is toggled by clicking on the extension icon.

Observation:
Apparently, when PDF files are configured to "View in Firefox", if there's an embedded PDF, Firefox will download the PDF *and* open the downloaded file in a new tab... :sweat_smile:
If that is undesired - I'm not sure if the PDF file type handling setting can be configured by an extension, so it might be that after toggling the extension's mode, the corresponding file type setting in Firefox's preferences needs to be changed manually.
