### ISSUE TITLE
[QUESTION] What exactly is improved?

### ISSUE THREAD

**Issue by ghost** [jaens/no-pdf-download#2]
Hi,

I'm wondering about what is exactly improved from _No PDF Download - Improved_ to  _No PDF Download_ by Merten Peetz.
Is it only _Fixes downloads & printing on Google Docs and Gmail_ (version 2.0.1) and _Fixed detection of PDFs in unconfigured Amazon S3 buckets._ (latest version 2.0.4) or is there more to it?

I've been running the original _No PDF Download_ by Merten Peetz for years, just tried _No PDF Download - Improved_ and both work flawlessly, but I linger to know exactly what differenciates them from one another.

Thanks!

**Comment by jaens** [comment]
Yes, that's exactly it, it resolves a few issues with the original extension on certain sites. I'll be adding more fixes as I find issues, just found another one.

Thank you for the feedback, I will probably update the description!
